// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package plugin

import (
	"github.com/gorilla/mux"
	"github.com/grafana/grafana-plugin-sdk-go/backend/log"
	"github.com/xiak/grafana-app-with-backend/pkg/internal/biz"
	"github.com/xiak/grafana-app-with-backend/pkg/internal/config"
	"github.com/xiak/grafana-app-with-backend/pkg/internal/data"
	"github.com/xiak/grafana-app-with-backend/pkg/internal/server"
	"github.com/xiak/grafana-app-with-backend/pkg/internal/service"
)

// Injectors from wire.go:

// wireApp init application.
func wireApp(confData *conf.Data, chat *conf.Chat, rag *conf.Rag, logger log.Logger) (*mux.Router, func(), error) {
	dataData, cleanup, err := data.NewData(confData, chat, rag, logger)
	if err != nil {
		return nil, nil, err
	}
	systemSecurityRepo := data.NewSystemSecurityRepo(dataData, logger)
	systemSecurityUsercase := biz.NewSystemSecurityUsercase(systemSecurityRepo, logger)
	chatRepo := data.NewChatRepo(dataData, logger)
	chatUsecase := biz.NewChatUsecase(chatRepo, logger)
	ragRepo := data.NewRagRepo(dataData, logger)
	ragUsecase := biz.NewSystemSecurityUsecase(ragRepo, logger)
	hostActivityRepo := data.NewHostActivityRepo(dataData, logger)
	hostActivityUsecase := biz.NewHostActivityUsecase(hostActivityRepo, logger)
	hostStateRepo := data.NewHostStateRepo(dataData, logger)
	hostStateUsecase := biz.NewHostStateUsecase(hostStateRepo, logger)
	networkErrorRepo := data.NewNetworkErrorRepo(dataData, logger)
	networkErrorUsecase := biz.NewNetworkUsecase(networkErrorRepo, logger)
	cpuStateRepo := data.NewCpuStateRepo(dataData, logger)
	cpuStateUsecase := biz.NewCpuStateUsecase(cpuStateRepo, logger)
	copilotService := service.NewCopilotService(systemSecurityUsercase, chatUsecase, ragUsecase, hostActivityUsecase, hostStateUsecase, networkErrorUsecase, cpuStateUsecase, logger)
	httpServer := server.NewHTTPServer(logger, copilotService)
	router := GetRouter(httpServer)
	return router, func() {
		cleanup()
	}, nil
}
