data:
  database:
    driver: mysql
    source: root:dangerous@tcp(127.0.0.1:3306)/test?parseTime=true
  prometheus:
    url: "0.0.0.0:9090"
  file:
    path: /tmp/test.data

chat:
  prompts:
    retrieve: 10
    keywords:
      - "2024年9月3日有无安全异常？"
      - "今日vvault运行有无异常情况？"
      - "我们当前APP访问主机资源情况怎么样？"

rag:
  prompts:
    keywords:
      - "服务器性能监测"
      - "服务器故障预警"
      - "服务器资源管理"
      - "服务器安全加固"
      - "服务器备份策略"
      - "服务器负载均衡"
      - "服务器日志分析"
      - "服务器软件更新"
      - "服务器高可用性"
      - "服务器容量规划"

